.github/workflows/README.md, backend/model/README.md, scripts/README.md
- frontend will eventually contain an app to interract with backend
- backend will contain the API and the model
- .github/workflows will contain our Github Actions
- Placeholder README.md in folder to push them in the repository
=> Add project structure and docker file placeholders

.env, backend/app/core/settings.py, backend/app/main.py, backend/pylintrc
- Servers are configurable using .env file
- For the moment, only the api port is opened to allow the access locally
=> backend: add cors middleware

backend/.devcontainer/devcontainer.json, backend/requirements.txt
Thanks to @GuetchArnaud for using a different architecture (Intel), we discovered our requirements were flawed.
It's now fixed.
=> Fix devcontainer json file and remove tensorflow-cpu-aws from requirements

backend/app/api/v1/api.py, backend/app/core/metadata.py, backend/app/main.py
=> Add API and tags metadata

backend/app/api/v1/endpoints/prediction.py, backend/datascience/classification.py, backend/pylintrc
Plus d'information dans les messages de commit et dans l'issue #31.
Closes #31.
=> Utilise seulement les modèles nécessaire à la prédiction

backend/.devcontainer/Dockerfile, backend/.devcontainer/devcontainer.json, backend/app/api/dependencies.py, backend/app/api/v1/endpoints/public.py, backend/app/core/settings.py, backend/app/tests/api/endpoints/test_login.py, backend/app/tests/api/endpoints/test_public.py, backend/app/tests/api/endpoints/test_users.py, backend/app/tests/conftest.py, backend/app/tests/utilities/user.py, backend/app/tests/utilities/utilities.py, backend/pylintrc, backend/pyrightconfig.json, backend/requirements-dev.txt
Review the commits one by one to understand what's going on.
Part of #41
=> Add a first batch of unit tests to the project

backend/app/api/dependencies.py, backend/app/api/v1/endpoints/login.py, backend/app/api/v1/endpoints/prediction.py, backend/app/api/v1/endpoints/prediction_feedback.py, backend/app/api/v1/endpoints/public.py, backend/app/api/v1/endpoints/users.py, backend/app/schemas/prediction_feedback.py, backend/app/tests/api/endpoints/test_login.py, backend/app/tests/api/endpoints/test_prediction_feedback.py, backend/app/tests/api/endpoints/test_public.py, backend/app/tests/api/endpoints/test_users.py, backend/app/tests/conftest.py, backend/app/tests/utilities/prediction_feedback.py, backend/app/tests/utilities/utilities.py, backend/requirements-dev.txt
As always, review the PR by viewing changes in each commit one by one.
Part of #41
=> Add unit tests for prediction_feedback and update endpoints and their tests

docker-compose.yaml, scripts/docker-deploy.sh, scripts/install-signoz.sh
=> Fix the error triggered when trying the network already exists

.env, .github/workflows/linter-and-tests.yaml, README.md, backend/.devcontainer/.env, backend/backend.Dockerfile, backend/scripts/lint.sh, backend/scripts/start.sh, scripts/docker-deploy.sh, scripts/run-tests.sh, scripts/tests/start-containers.sh
Actions now have an environment to work in. It'll be important for CD.
Part of #33
=> Update actions and add environment selection in scripts

.devcontainer/Dockerfile, .devcontainer/onCreateCommand.sh
The goal is to not have to download them again everytime we open the container
=> Move ZSH configuration into Dockerfile

.devcontainer/Dockerfile, .devcontainer/onCreateCommand.sh, .gitignore, .mookme.json, .vscode/tasks.json, backend/.hooks/pre-commit.json, backend/scripts/lint.sh, package-lock.json, package.json, scripts/environment-setup.sh
- Add package.json and package-lock.json
- Update environment-setup.sh to install mookme and install hooks
- Run lint.sh and start-tests.sh when editing files in backend
=> Add moonkme to the project to run sub-project pre-commit hooks

.devcontainer/Dockerfile, README.md, backend/.vscode/tasks.json, backend/scripts/start-reload.sh, scripts/environment-setup.sh
Ajoute un plugin Poetry pour charger le contenu du fichier .env lorsqu'on exécute des commandes avec la fonction run :
```shell
poetry run [...]
```
Closes #65
=> Fix issue regarding tasks not having access to up to date .env

backend/pyproject.toml, datascience/pyproject.toml
Mise à jour des fichiers pyproject pour ajouter des metadatas.
=> Add metadata to pyproject files

.github/workflows/commit_lint.yaml
=> ci: :construction_worker: add commitlint Github action

README.md
=> readme file change for test

backend/app/tests/api/v1/endpoints/test_prediction.py
=> chore(backend): add TODO tag regarding a new fixture

.env, datascience/poetry.lock, datascience/pyproject.toml, datascience/pyrightconfig.json, datascience/scripts/optimize_images.py, datascience/scripts/train_image_model.py, datascience/src/core/custom_errors.py, datascience/src/core/logging_config.py, datascience/src/core/logging_filters.py, datascience/src/core/settings.py, datascience/src/utilities/dataset_utils.py, pyrightconfig.json, ruff.toml
Closes #83
Les TODO et correction du linter et type checker pointent vers l'issue #103.
A noter que le dossier `--input-dir` du script `optimize_images.py` contient les données fournies dans le challenge Rakuten, à savoir : 
```txt
data/originals
├── X.csv
├── images
└── y.csv
```
```txt
❯ python -m scripts.optimize_images --train-size 0.01 --test-size 0.01 --input-dir "data/originals" --output-dir "data/datasets/temp" >> optimize_images.txt
Transformation du jeu de données d'entrainement
Avancement :  69.11 %
Temps restant : 0:00:01
Avancement : 100%
Transformation du jeu de données de test
Avancement :  69.86 %
Temps restant : 0:00:01
Avancement : 100%
Enregistrement des données
```
```txt
❯ python -m scripts.train_image_model --input-dir "data/datasets/temp/" --output-dir …
```
=> 83 image model

datascience/scripts/optimize_images.py, datascience/scripts/train_image_model.py, datascience/scripts/train_text_model.py, datascience/src/utilities/dataset_utils.py, datascience/src/utilities/model_eval.py, ruff.toml
Refs: #103
```txt
❯ python -m scripts.train_text_model --train-patience 2 --input-dir "data/datasets/fusion_model" --output-dir "data/models/text" &> text_training_log.txt
Script started
Load data
Extract features and target
Create preprocessor and preprocess features
Create datasets
Build text model
WARNING in optimizer.__init__, line 70: At this time, the v2.11+ optimizer `tf.keras.optimizers.Adam` runs slowly on M1/M2 Macs, please use the legacy Keras optimizer instead, located at `tf.keras.optimizers.legacy.Adam`.
WARNING in __init__.get, line 292: There is a known slowdown when using v2.11+ Keras optimizers on M1/M2 Macs. Falling back to the legacy Keras optimizer, i.e., `tf.keras.optimizers.legacy.Adam`.
Model: "sequential" …
```
=> refactor(datascience): use functions to evaluate model performance

README.md, datascience/poetry.lock, datascience/scripts/train_image_model.py, datascience/src/core/settings.py, datascience/src/utilities/dataset_utils.py, datascience/src/utilities/model_eval.py
Update MLFlow to latest version as well.
Closes #114
=> feat(datascience): track metrics and artifacts with MLFlow

datascience/scripts/train_fusion_model.py, datascience/scripts/train_image_model.py, datascience/scripts/train_text_model.py, datascience/src/core/custom_errors.py, datascience/src/core/settings.py, datascience/src/utilities/model_utils.py
=> feat(datascience): text model training tracking with MLFlow

datascience/scripts/train_image_model.py
- Fix requirements not being provided correctly to MLFlow.
- Change model format to use .tf instead of .h5.
- Fix warning regarding optimizer on Apple Silicon.
Closes #128
=> fix(datascience): requirements, model file format and optimizer

datascience/scripts/train_fusion_model.py, datascience/scripts/train_image_model.py, datascience/scripts/train_text_model.py, datascience/src/core/constants.py, datascience/src/core/settings.py, datascience/src/transformers/text_transformer.py, datascience/src/utilities/dataset_utils.py, datascience/src/utilities/mlflow_utils.py, datascience/src/utilities/model_utils.py, mypy.ini
This PR is quite massive since I had to edit the other models to handle the changes done with Fusion model.
As of today, we finally have all models implemented and usable thought `mlflow model serve`.
Closes #116 , Closes #117 and Closes #131
=> Track fusion model with MLFlow and fix / improve other models

README.md, datascience/scripts/train_fusion_model.py, datascience/src/transformers/text_transformer.py
Update README with instruction regarding the models.
Refs: #117
=> fix(datascience): fix issue with text_preprocessor

datascience/scripts/optimize_images.py
The error could have been detected if we didn't
disable mypy for the whole file.
Closes #138
=> fix(datascience): optimize_images works again

.dockerignore, .gitignore, datascience/datascience.Dockerfile, datascience/poetry.lock, datascience/pyproject.toml, datascience/scripts/download_mlruns.py, datascience/scripts/rename-artifacts.sh, datascience/scripts/start.sh, datascience/src/core/settings.py, docker-compose.yaml, scripts/demo.env, scripts/docker-deploy.sh
Default mlruns folder is downloaded from Google Drive and inserted into docker image.
Closes #113
Closes #143
=> feat(datascience): containerize datascience

.github/workflows/backend_lint_tests.yaml, datascience/poetry.lock, datascience/pyproject.toml, scripts/docker-deploy.sh, scripts/run-tests-in-containers.sh
=> ci: fix backend unit tests

README.md
=> chore: delete frontend placeholder

.github/workflows/deploy-docs.yml
Add the possibility to manually trigger the workflow.
Refs: #54
=> build: remove docs deployment on pr

docs/content/Developer/Documentation.md
This page is not done yet, but the merge is done to demo the result to the team.
Refs: #54
=> docs: developer page regarding documentation

docs/content/.obsidian/app.json, docs/content/Developer/Documentation.md
=> docs: update link to an image to fix retrieving issues
